apiVersion: v1
kind: Service
metadata:
  name: meeting-room-booking
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: meeting-room-booking
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meeting-room-booking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meeting-room-booking
  template:
    metadata:
      labels:
        app: meeting-room-booking
    spec:
      containers:
      - image: meeting-room-booking:latest
        imagePullPolicy: Never
        name: app
